// <auto-generated />
using System;
using MatdanSathi.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatdanSathi.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatdanSathi.API.Domain.Entities.BloCoordinateMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloContactEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoundaryCoordinatesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PollingStationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BloCoordinateMaps");
                });

            modelBuilder.Entity("MatdanSathi.API.Domain.Entities.VerificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("VerificationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VoterProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoterProfileId");

                    b.ToTable("VerificationLogs");
                });

            modelBuilder.Entity("MatdanSathi.API.Domain.Entities.VoterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AssemblyConstituency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloContactEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirthEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EpicNumberBlindIndex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EpicNumberEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNameEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PollingStationLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PollingStationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EpicNumberBlindIndex")
                        .IsUnique();

                    b.ToTable("VoterProfiles");
                });

            modelBuilder.Entity("MatdanSathi.API.Domain.Entities.VerificationLog", b =>
                {
                    b.HasOne("MatdanSathi.API.Domain.Entities.VoterProfile", "VoterProfile")
                        .WithMany()
                        .HasForeignKey("VoterProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VoterProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
